server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_db?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: root

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    #将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
    # 加上该注解，可在后台打印sql，方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#引入swagger
swagger:
  enable: true